library(readxl)
library(here)

here::set_here()
ECON_GDP_per_cap <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "B12:F22")
ECON_GNI_per_cap <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "H12:L22")
ECON_POP <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "B26:F36")
ECON_POP_DEN <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "H26:L36")
ECON_HEALTHCARE_per_cap <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "B40:F50")
ECON_HOUSEHOLD_SAVINGS <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "H40:L50")
ECON_EURO_TO_DOUBLOON_CONVERSION <- read_excel("data/economic.xlsx",sheet = "Rarita Economic",range= "B54:D59")
ECON_SPOT_RATE <- read_excel("data/economic.xlsx",sheet = "Rarita Spot Rates",range= "B12:P72")
ECON_ANNUAL_INFLATION_RATE <- read_excel("data/economic.xlsx",sheet = "Rarita Inflation Rates",range= "B11:C41")
ECON_GDP_per_cap_OTHER<- read_excel("data/economic.xlsx",sheet = "Other Countries GDP",range= "B12:G32")

FINS_Revenue <- read_excel("data/football-finance.xlsx",sheet = "Revenue",range= "B13:V34")
FINS_Expense <- read_excel("data/football-finance.xlsx",sheet = "Expense",range= "B13:Q34")
FINS_Attendance <- read_excel("data/football-finance.xlsx",sheet = "Attendance",range= "B13:C34")
FINS_Social_Media <- read_excel("data/football-finance.xlsx",sheet = "Social Media",range= "B13:G34")

colnames(FINS_Revenue) <- paste(colnames(FINS_Revenue),c("",rep(2020:2016, each = 4, len = 20)))
colnames(FINS_Expense) <- paste(colnames(FINS_Expense),c("",rep(2020:2016, each = 4, len = 20)))

PLAYER_league_shoot <- read_excel("data/player.xlsx",sheet = "League Shooting",range= "B12:AA5566")
PLAYER_league_pass <- read_excel("data/player.xlsx",sheet = "League Passing",range= "B12:AF5566")
PLAYER_league_def <- read_excel("data/player.xlsx",sheet = "League Defense",range= "B12:AG5566")
PLAYER_league_goal <- read_excel("data/player.xlsx",sheet = "League Goalkeeping",range= "B12:AB425")

PLAYER_tourn_shoot <- read_excel("data/player.xlsx",sheet = "Tournament Shooting",range= "B12:Z2027")
PLAYER_tourn_pass <- read_excel("data/player.xlsx",sheet = "Tournament Passing",range= "B12:AE500")
PLAYER_tourn_def <- read_excel("data/player.xlsx",sheet = "Tournament Defense",range= "B12:AF500")
PLAYER_tourn_goal <- read_excel("data/player.xlsx",sheet = "Tournament Goalkeeping",range= "B12:AA141")

PLAYER_salary2020 <- read_excel("data/player.xlsx",sheet = "2020 Salaries",range= "B12:G2744")
PLAYER_salary2021 <- read_excel("data/player.xlsx",sheet = "2021 Salaries",range= "B12:G2834")